version: '3.3'

services:

  app:
    build: 
      context: ..
      dockerfile: ./docker/app/Dockerfile

    expose: 
      - 8000

    environment:
      - RUN_MODE=production
      - DB_USER=${COMPOSE_DB_USER}
      - DB_PASS=${COMPOSE_DB_PASSWORD}

    depends_on:
      - postgres


  postgres:
    build:
      context: ..
      dockerfile: ./docker/postgres/Dockerfile

    volumes:
      - data-volume:/var/lib/postgresql/data

    expose:
      - 5432

    environment:
      - POSTGRES_USER=${COMPOSE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${COMPOSE_POSTGRES_PASSWORD}


  nginx:
    build: ./nginx

    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - app

volumes:
  data-volume:
    driver: local

  certs:
    driver: local

  certs-data:
    driver: local
