user_locations =  [
    "University of Central Florida",
    "Texas A&M University",
    "Florida International University",
    "Ohio State University",
    "University of Maryland - College Park",
    "Arizona State University - Tempe",
    "Pennsylvania State University",
    "Michigan State University",
    "University of Houston",
    "California State University - Northridge",
    "California State University - Fullerton",
    "Rutgers University - New Brunswick",
    "University of Minnesota - Twin Cities",
    "University of Florida",
    "Utah Valley University",
    "Texas State University",
    "University of Arizona",
    "Indiana University - Bloomington",
    "University of Texas - Arlington",
    "University of Alabama",
    "Florida State University",
    "Kennesaw State University",
    "Purdue University",
    "University of South Florida"
    "California State University - Long Beach",
    "University of North Texas",
    "University of Wisconsin - Madison",
    "University of California - Los Angeles",
    "Texas Tech University",
    "Iowa State University",
    "San Diego State University",
    "University of Michigan - Ann Arbor",

    "Massachusetts Institute of Technology",
    "University of Washington",
    "University of Washington - Bothell",
    "University of California - Berkeley",
    "University of Illinois - Urbana-Champaign",
    "University of Texas - Austin",
    "University of Waterloo",
    "Georgia Institute of Technology",
    "Stanford University",
    "California Institute of Technology"
]


