user_locations =  [
    "Academy of Cosmetology, L.L.C.",
    "Academy of Interactive Entertainment",
    "Alpine College",
    "ALPS Language School",
    "Bakke Graduate University",
    "Bastyr University",
    "Bates Technical College",
    "Beauty Academy",
    "Bellevue College",
    "Bellingham Beauty School",
    "Bellingham Technical College",
    "Big Bend Community College",
    "BJ's Beauty and Barber College",
    "Bryman College",
    "Cambridge College - WA",
    "Cascadia Community College",
    "Central Washington University",
    "Centralia College",
    "Chetta's Academy of Hair and Nails",
    "City University of Seattle",
    "Clark College",
    "Clover Park Technical College",
    "Columbia Basin College",
    "Cornish College of the Arts",
    "Cortiva Institute - Brian Utting School of Massage",
    "Cortiva Institute - Seattle",
    "Court Reporting Institute - Seattle",
    "Crace, Inc. Dale Carnegie Training",
    "CRI Career Training",
    "Crown College",
    "DigiPen Institute of Technology",
    "Divers Institute of Technology",
    "Dominion College",
    "Eastern Washington University",
    "Edmonds Community College",
    "Embassy CES",
    "Everest College - Bremerton",
    "Everest College - Lynnwood",
    "Everest College - Renton",
    "Everest College - Seattle",
    "Everett Community College",
    "Evergreen Beauty and Barber College",
    "Evergreen Beauty and Barber College - Bellevue",
    "Evergreen Healthcare",
    "Faith Evangelical College and Seminary",
    "Franciscan Health",
    "Gary Manuel Aveda Institute",
    "Gene Juarez Academy North Seattle",
    "Gene Juarez Academy South Seattle",
    "Glen Dow Academy of Hair Design and Salons, Inc.",
    "Gonzaga University",
    "Good Samaritan Hospital",
    "GP Institute of Cosmetology",
    "Grays Harbor College",
    "Green River Community College",
    "Group Health Cooperative Seattle",
    "Group Health Cooperative Tacoma",
    "Henry Cogswell College",
    "Heritage University",
    "Highline Community College",
    "Inland Massage Institute, Inc.",
    "Interface College",
    "International Air and Hospitality Academy",
    "International Beauty Education Center",
    "ITT Technical Institute - Spokane Valley",
    "Jonathan M. Wainwright Memorial VA Medical Center",
    "Kaplan College - Seattle Campus",
    "Kirkland Beauty School",
    "Lake Washington Institute of Technology",
    "Lower Columbia College",
    "Lower Columbia Enterprises, Inc. DBA Stylemasters College of Hair Design",
    "Madigan Army Medical Center",
    "Madigan Army Medical Center/Ft. Lewis Dental Activity Advanced Education in General Dentistry 12 Months",
    "Mann-Grandstaff VA Medical Center",
    "Middle Way Acupuncture Institute",
    "Montessori Center for Teacher Education - Washington State",
    "Montessori College for Early Education",
    "Montessori Education Institute/Pacific NW",
    "Montessori Schools of Washington",
    "Montessori Teacher Preparation of Washington",
    "Mukogawa Fort Wright Institute",
    "North Seattle Community College",
    "Northwest Aviation College",
    "Northwest Baptist Seminary",
    "Northwest College of Art",
    "Northwest Hair Academy, Mount Vernon",
    "Northwest HVAC/R Training Center",
    "Northwest Indian College",
    "Northwest Institute of Literary Arts",
    "Northwest Regional Training Center",
    "Northwest School of Wooden Boatbuilding",
    "Northwest University",
    "Olympic College",
    "Pacific Lutheran University",
    "Pacific Northwest Ballet School",
    "Pacific Northwest University of Health Sciences",
    "Paroba College of Cosmetology",
    "Paul Mitchell The School Richland",
    "Paul Mitchell the School Spokane",
    "Peace Health St. Joseph Hospital",
    "Peninsula College",
    "Perry Technical Institute",
    "Phagans Orchards Beauty School",
    "Photographic Center Northwest",
    "Pierce College at Puyallup",
    "Pinchot University",
    "Professional Beauty School",
    "Providence St Peter Hospital",
    "Puget Sound Christian College",
    "Renton Technical College",
    "Saint Martin's University",
    "Sakie International College of Cosmetology",
    "School of Piano Technology for the Blind",
    "Sea Mar Community Health Center",
    "Seattle Central College",
    "Seattle Film Institute",
    "Seattle Institute of Oriental Medicine",
    "Seattle Midwifery School",
    "Seattle Pacific University",
    "Seattle University",
    "Seattle Vocational Institute",
    "Shoreline Community College",
    "Skagit Valley College",
    "South Puget Sound Community College",
    "South Seattle College",
    "Spokane College of English Language",
    "Spokane Community College",
    "Spokane Falls Community College",
    "Spokane Mental Health",
    "Spring Valley Montessori Teacher Education Program",
    "Studio Beauty School",
    "Summit Salon Academy",
    "Sunnyside Beauty Academy",
    "Swedish Health Services",
    "Tacoma Community College",
    "The Art Institute of Seattle",
    "The Evergreen State College",
    "The Seattle School of Theology and Psychology",
    "Total Cosmetology Training Center",
    "Tri-Cities Chaplaincy",
    "Trinity Lutheran College",
    "University of Puget Sound",
    "University of Washington",
    "University of Washington - Bothell",
    "VA Puget Sound Health Care System - American Lake Division",
    "VA Puget Sound Health Care System - Seattle Division",
    "Victoria's Academy of Cosmetology",
    "Walla Walla Community College",
    "Walla Walla University",
    "Washington State University",
    "Wenatchee Valley College",
    "Western State Hospital",
    "Western Washington University",
    "Whatcom Community College",
    "Whitman College",
    "Whitworth University",
    "Wu Hsing Tao School",
    "Yakima Valley Community College"

    "University of California - Berkeley",
    "University of Illinois - Urbana-Champaign",
    "University of Texas - Austin",
    "Georgia Institute of Technology",
    "Stanford University",
    "California Institute of Technology"
]


